name: penny

services:
    php:
        build:
            target: dev
        container_name: penny-php
        ports:
            - ${APP_PORT:-80}:80
            - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
        volumes:
            - .:/var/www/html
        networks:
            penny:
        depends_on:
            - mysql
    mysql:
        image: mysql:latest
        container_name: penny-mysql
        ports:
            - ${FORWARD_DB_PORT:-3306}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - penny-mysql:/var/lib/mysql
        networks:
            - penny
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - -p${DB_PASSWORD}
            retries: 3
            timeout: 5s

    phpmyadmin:
        container_name: penny-phpmyadmin
        image: phpmyadmin:latest
        depends_on:
            - mysql
        ports:
            - ${PMA_PORT:-8080}:80
        networks:
            penny:
        environment:
            - PMA_USER=${PMA_USER:-root}
            - PMA_PASSWORD=${PMA_PASSWORD:-password}
            - PMA_HOST=mysql
            - PMA_QUERYHISTORYDB=true
networks:
    penny:
volumes:
    penny-mysql:
